- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: >
      deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]
      https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins to apply Docker group membership
  service:
    name: jenkins
    state: restarted

- name: Enable Jenkins service
  service:
    name: jenkins
    enabled: yes
    state: started

- name: Check if initial admin password exists
  stat:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: admin_pass_file

- name: Get initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  changed_when: false
  when: admin_pass_file.stat.exists

- name: Output initial admin password
  debug:
    msg: "{{ initial_admin_password.stdout }}"
  when: admin_pass_file.stat.exists