- name: Add Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /tmp/jenkins.key
    mode: '0644'

- name: Dearmor Jenkins key
  command: gpg --dearmor -o /etc/apt/keyrings/jenkins.gpg /tmp/jenkins.key
  args:
    creates: /etc/apt/keyrings/jenkins.gpg

- name: Add Jenkins repository
  apt_repository:
    repo: >
      deb [signed-by=/etc/apt/keyrings/jenkins.gpg]
      https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Enable Jenkins service
  service:
    name: jenkins
    enabled: yes
    state: started

- name: Get initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  changed_when: false

- name: Output initial admin password
  debug:
    msg: "{{ initial_admin_password.stdout }}"