plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  "tag:Role": bastion-host
keyed_groups:
  - key: tags.Role
    prefix: role
    separator: "_"
hostnames:
  - public_ip_address
compose:
  ansible_host: public_ip_address