ansible_user: ubuntu
ansible_ssh_private_key_file: ../keys/admin.pem
ansible_ssh_common_args: >-
  -o ForwardAgent=yes
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -W %h:%p -q ubuntu@{{ hostvars[groups['role_bastion_host'][0]]['ansible_host'] }}"