ansible_user: ubuntu
# Add quotes here
ansible_ssh_private_key_file: "{{ playbook_dir }}/../keys/jenkins.pem"

ansible_ssh_common_args: |
  -o ForwardAgent=yes
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand="ssh -i {{ playbook_dir }}/../keys/bastion_admin.pem -W %h:%p -q ubuntu@{{ hostvars[groups['role_bastion_host'][0]]['ansible_host'] }}"