---
- name: Configure Bastion Host
  hosts: role_bastion_host
  become: yes
  remote_user: ubuntu
  roles:
    - common
    - docker
    - aws_cli
    - kubectl

- name: Configure Jenkins Controller Server
  hosts: role_jenkins_controller
  become: yes
  remote_user: ubuntu
  roles:
    - common
    - java
    - docker
    - trivy
    - aws_cli
    - jenkins